# This wrangler.toml file is not used for deploying the Pages project.
# It is needed so that Wrangler can run the d1 commands to create the db and process migrations.
name = "wildebeest"
main = "src/index.ts"
compatibility_date = "2022-12-05"
compatibility_flags = ['nodejs_compat']

# Specify your account id here so that all commands run agains the correct account.
account_id = "4fcde8c2eec955606a424036be89b32e"
[[d1_databases]]
binding = "DATABASE"
database_name = "wildebeest-mrtakedi-v1"
database_id = "6dc96652-0ec7-48fd-a67e-61436e88b440" 
