name: Pull request checks
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/PRs.yml'
      - '*.md'
      - 'docs/**'
      - 'renovate.json'
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/PRs.yml'
      - '*.md'
      - 'docs/**'
      - 'renovate.json'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-api:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Setup node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 18

      - name: Install
        run: corepack pnpm install

      - name: Build
        run: npm run build

      - name: Run API tests
        run: npm run test

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Setup node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 18

      - name: Install
        run: corepack pnpm install && corepack pnpm --dir frontend install

      - name: Check formatting
        run: npm run pretty

      - name: Check backend linting
        run: npm run lint:backend

      - name: Check consumer linting
        run: npm run lint:consumer

      - name: Check functions linting
        run: npm run lint:functions

      - name: Check frontend linting
        run: npm run lint:frontend

      - name: Check frontend types
        run: npm --prefix frontend run types-check

      - name: Checkout shuymn/sqldef
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          repository: shuymn/sqldef
          ref: refs/heads/support-sqlite3-trigger
          path: sqldef

      - name: Setup Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4
        with:
          go-version: '1.20'

      - name: Build sqldef
        working-directory: sqldef
        run: |
          make deps
          make build

      - name: Check DB schema
        run: |
          npm run database:migrate -- --local
          ./sqldef/build/linux-amd64/sqlite3def --enable-drop-table --config sqldef.yml --dry-run .wrangler/state/d1/DATABASE.sqlite3 < schema.sql | head -n 1 | grep -E '^-- Nothing is modified --$'

  test-ui:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Setup node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 18
      - name: Install dependencies
        run: corepack pnpm install
      - name: Run App in the background
        run: npm run ci-dev-test-ui &
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
